/* File: fotmmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Sep 17 15:11:05 2018
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fotm_error;
static PyObject *fotm_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fotm_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fotm_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(calctmat,CALCTMAT)(double*,double*,double*,double*,double*,double*,int*,double*,int*,int*);
extern void F_FUNC(calcampl,CALCAMPL)(int*,double*,double*,double*,double*,double*,double*,double*,complex_double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** calctmat **********************************/
static char doc_f2py_rout_fotm_calctmat[] = "\
nmax = calctmat(axi,rat,lam,mrr,mri,eps,np,ddelt,ndgs)\n\nWrapper for ``calctmat``.\
\n\nParameters\n----------\n"
"axi : input float\n"
"rat : input float\n"
"lam : input float\n"
"mrr : input float\n"
"mri : input float\n"
"eps : input float\n"
"np : input int\n"
"ddelt : input float\n"
"ndgs : input int\n"
"\nReturns\n-------\n"
"nmax : int";
/* extern void F_FUNC(calctmat,CALCTMAT)(double*,double*,double*,double*,double*,double*,int*,double*,int*,int*); */
static PyObject *f2py_rout_fotm_calctmat(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double axi = 0;
  PyObject *axi_capi = Py_None;
  double rat = 0;
  PyObject *rat_capi = Py_None;
  double lam = 0;
  PyObject *lam_capi = Py_None;
  double mrr = 0;
  PyObject *mrr_capi = Py_None;
  double mri = 0;
  PyObject *mri_capi = Py_None;
  double eps = 0;
  PyObject *eps_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  double ddelt = 0;
  PyObject *ddelt_capi = Py_None;
  int ndgs = 0;
  PyObject *ndgs_capi = Py_None;
  int nmax = 0;
  static char *capi_kwlist[] = {"axi","rat","lam","mrr","mri","eps","np","ddelt","ndgs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO:fotm.calctmat",\
    capi_kwlist,&axi_capi,&rat_capi,&lam_capi,&mrr_capi,&mri_capi,&eps_capi,&np_capi,&ddelt_capi,&ndgs_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ddelt */
    f2py_success = double_from_pyobj(&ddelt,ddelt_capi,"fotm.calctmat() 8th argument (ddelt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lam */
    f2py_success = double_from_pyobj(&lam,lam_capi,"fotm.calctmat() 3rd argument (lam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable eps */
    f2py_success = double_from_pyobj(&eps,eps_capi,"fotm.calctmat() 6th argument (eps) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mrr */
    f2py_success = double_from_pyobj(&mrr,mrr_capi,"fotm.calctmat() 4th argument (mrr) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ndgs */
    f2py_success = int_from_pyobj(&ndgs,ndgs_capi,"fotm.calctmat() 9th argument (ndgs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable rat */
    f2py_success = double_from_pyobj(&rat,rat_capi,"fotm.calctmat() 2nd argument (rat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mri */
    f2py_success = double_from_pyobj(&mri,mri_capi,"fotm.calctmat() 5th argument (mri) can't be converted to double");
  if (f2py_success) {
  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"fotm.calctmat() 7th argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable axi */
    f2py_success = double_from_pyobj(&axi,axi_capi,"fotm.calctmat() 1st argument (axi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nmax */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&axi,&rat,&lam,&mrr,&mri,&eps,&np,&ddelt,&ndgs,&nmax);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",nmax);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable nmax */
  } /*if (f2py_success) of axi*/
  /* End of cleaning variable axi */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  } /*if (f2py_success) of mri*/
  /* End of cleaning variable mri */
  } /*if (f2py_success) of rat*/
  /* End of cleaning variable rat */
  } /*if (f2py_success) of ndgs*/
  /* End of cleaning variable ndgs */
  } /*if (f2py_success) of mrr*/
  /* End of cleaning variable mrr */
  } /*if (f2py_success) of eps*/
  /* End of cleaning variable eps */
  } /*if (f2py_success) of lam*/
  /* End of cleaning variable lam */
  } /*if (f2py_success) of ddelt*/
  /* End of cleaning variable ddelt */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of calctmat ******************************/

/********************************** calcampl **********************************/
static char doc_f2py_rout_fotm_calcampl[] = "\
s,z = calcampl(nmax,lam,thet0,thet,phi0,phi,alpha,beta)\n\nWrapper for ``calcampl``.\
\n\nParameters\n----------\n"
"nmax : input int\n"
"lam : input float\n"
"thet0 : input float\n"
"thet : input float\n"
"phi0 : input float\n"
"phi : input float\n"
"alpha : input float\n"
"beta : input float\n"
"\nReturns\n-------\n"
"s : rank-2 array('D') with bounds (2,2)\n"
"z : rank-2 array('d') with bounds (4,4)";
/* extern void F_FUNC(calcampl,CALCAMPL)(int*,double*,double*,double*,double*,double*,double*,double*,complex_double*,double*); */
static PyObject *f2py_rout_fotm_calcampl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*,double*,double*,complex_double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  double lam = 0;
  PyObject *lam_capi = Py_None;
  double thet0 = 0;
  PyObject *thet0_capi = Py_None;
  double thet = 0;
  PyObject *thet_capi = Py_None;
  double phi0 = 0;
  PyObject *phi0_capi = Py_None;
  double phi = 0;
  PyObject *phi_capi = Py_None;
  double alpha = 0;
  PyObject *alpha_capi = Py_None;
  double beta = 0;
  PyObject *beta_capi = Py_None;
  complex_double *s = NULL;
  npy_intp s_Dims[2] = {-1, -1};
  const int s_Rank = 2;
  PyArrayObject *capi_s_tmp = NULL;
  int capi_s_intent = 0;
  double *z = NULL;
  npy_intp z_Dims[2] = {-1, -1};
  const int z_Rank = 2;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  static char *capi_kwlist[] = {"nmax","lam","thet0","thet","phi0","phi","alpha","beta",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:fotm.calcampl",\
    capi_kwlist,&nmax_capi,&lam_capi,&thet0_capi,&thet_capi,&phi0_capi,&phi_capi,&alpha_capi,&beta_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"fotm.calcampl() 1st argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lam */
    f2py_success = double_from_pyobj(&lam,lam_capi,"fotm.calcampl() 2nd argument (lam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable phi */
    f2py_success = double_from_pyobj(&phi,phi_capi,"fotm.calcampl() 6th argument (phi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable thet */
    f2py_success = double_from_pyobj(&thet,thet_capi,"fotm.calcampl() 4th argument (thet) can't be converted to double");
  if (f2py_success) {
  /* Processing variable thet0 */
    f2py_success = double_from_pyobj(&thet0,thet0_capi,"fotm.calcampl() 3rd argument (thet0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable beta */
    f2py_success = double_from_pyobj(&beta,beta_capi,"fotm.calcampl() 8th argument (beta) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s */
  s_Dims[0]=2,s_Dims[1]=2;
  capi_s_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_s_tmp = array_from_pyobj(NPY_CDOUBLE,s_Dims,s_Rank,capi_s_intent,Py_None);
  if (capi_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fotm_error,"failed in converting hidden `s' of fotm.calcampl to C/Fortran array" );
  } else {
    s = (complex_double *)(PyArray_DATA(capi_s_tmp));

  /* Processing variable phi0 */
    f2py_success = double_from_pyobj(&phi0,phi0_capi,"fotm.calcampl() 5th argument (phi0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alpha */
    f2py_success = double_from_pyobj(&alpha,alpha_capi,"fotm.calcampl() 7th argument (alpha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
  z_Dims[0]=4,z_Dims[1]=4;
  capi_z_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_z_tmp = array_from_pyobj(NPY_DOUBLE,z_Dims,z_Rank,capi_z_intent,Py_None);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fotm_error,"failed in converting hidden `z' of fotm.calcampl to C/Fortran array" );
  } else {
    z = (double *)(PyArray_DATA(capi_z_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nmax,&lam,&thet0,&thet,&phi0,&phi,&alpha,&beta,s,z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_s_tmp,capi_z_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of alpha*/
  /* End of cleaning variable alpha */
  } /*if (f2py_success) of phi0*/
  /* End of cleaning variable phi0 */
  }  /*if (capi_s_tmp == NULL) ... else of s*/
  /* End of cleaning variable s */
  } /*if (f2py_success) of beta*/
  /* End of cleaning variable beta */
  } /*if (f2py_success) of thet0*/
  /* End of cleaning variable thet0 */
  } /*if (f2py_success) of thet*/
  /* End of cleaning variable thet */
  } /*if (f2py_success) of phi*/
  /* End of cleaning variable phi */
  } /*if (f2py_success) of lam*/
  /* End of cleaning variable lam */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of calcampl ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"calctmat",-1,{{-1}},0,(char *)F_FUNC(calctmat,CALCTMAT),(f2py_init_func)f2py_rout_fotm_calctmat,doc_f2py_rout_fotm_calctmat},
  {"calcampl",-1,{{-1}},0,(char *)F_FUNC(calcampl,CALCAMPL),(f2py_init_func)f2py_rout_fotm_calcampl,doc_f2py_rout_fotm_calcampl},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fotm",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_fotm(void) {
#else
#define RETVAL
PyMODINIT_FUNC initfotm(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = fotm_module = PyModule_Create(&moduledef);
#else
  m = fotm_module = Py_InitModule("fotm", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fotm (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'fotm' is auto-generated with f2py (version:2).\nFunctions:\n"
"  nmax = calctmat(axi,rat,lam,mrr,mri,eps,np,ddelt,ndgs)\n"
"  s,z = calcampl(nmax,lam,thet0,thet,phi0,phi,alpha,beta)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  fotm_error = PyErr_NewException ("fotm.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fotm");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
